### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by krsudhar** [WolframResearch/WolframWebEngineForPython#1]
Hi,

Excellent documentation of Wolfram Web Engine.
 I have Wolfram engine, I also have python in my system. But I am using Windows 10 OS. 
How do i run this from my system?
Help would be really appreciated

**Comment by arnoudbuzing** [comment]
What have you tried so far, and where did you get stuck?

**Comment by krsudhar** [comment]
I have downloaded cloned all files from the git hub. I am looking for instrcutions to start

**Comment by arnoudbuzing** [comment]
Are the README instructions not sufficient? If not, where exactly do you get stuck in those instructions?

https://github.com/WolframResearch/WolframWebEngineForPython/blob/master/README.md

**Comment by krsudhar** [comment]
Looks like Readme instrcutions are for ubuntu OS. What are the instructions for windows OS?

**Comment by riccardodivirgilio** [comment]
Instructions are cross platform, the same command works on mac / windows / linux.

just install python3, open the command line and run the commands in the readme

https://www.howtogeek.com/235101/10-ways-to-open-the-command-prompt-in-windows-10/

the most important is:

`path/to/python3.exe -m pip install wolframwebengine`

where are you exactly stuck?

**Comment by riccardodivirgilio** [comment]
@krsudhar let me know if there is anything I can help you with otherwise I'll close this issue in a few days.

Thanks.
