### ISSUE TITLE
Load resources at web engine startup

### ISSUE THREAD

**Issue by jcromwell** [WolframResearch/WolframWebEngineForPython#2]
I'm enjoying using the Wolfram Web Engine.
I'd like to load some resources (specifically a classifier object) from Wolfram Cloud into memory when the server starts up, rather than at the time of an API call.
Is there a way to specify this into an "initialization" file that is consumed at server startup?
Many thanks!
John

**Comment by arnoudbuzing** [comment]
You mean something like this: https://reference.wolfram.com/language/ref/file/init.m.html ?

**Comment by jcromwell** [comment]
This is terrific. I wasn't aware of the flexible init options.
Many thanks for this suggestion! I'll give it a try.
John

**Comment by riccardodivirgilio** [comment]
Yes, for this project we don't rely on anything custom. Let me know if you need anything else.

Riccardo.

**Comment by arnoudbuzing** [comment]
Additionally there are a number of Wolfram Language functions which help with persistence and initialization of values:

* https://reference.wolfram.com/language/guide/SettingPersistentValues.html
* https://reference.wolfram.com/language/guide/InitializationAndProvisioning.html
* https://reference.wolfram.com/language/guide/WolframSystemSetup.html

Good luck with your project!
